/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sentenciascontrol;

/**
 *
 * @author José Alejandro Durán
 */
public class Arreglo2 extends javax.swing.JInternalFrame{

    /**
     * Creates new form Arreglo2
     */
    public Arreglo2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lMensaje1 = new javax.swing.JLabel();
        lMatriz = new javax.swing.JLabel();
        lMultiplicar = new javax.swing.JLabel();
        tfEscalar = new javax.swing.JTextField();
        bVerResultado = new javax.swing.JButton();
        lMensaje2 = new javax.swing.JLabel();
        lMatrizb = new javax.swing.JLabel();
        bSumarAyB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Matriz Bidimensional");

        lMensaje1.setText("Dada la siguiente matriz A:");

        lMatriz.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lMatriz.setText("int[][] matrizA ={{10, 15, 20}, {-3, 12, 4}, {0, 5, -4}};");

        lMultiplicar.setText("Multiplicar por el escalar K: ");

        bVerResultado.setText("Ver Resultado");

        lMensaje2.setText("Dada la siguiente matriz B:");

        lMatrizb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lMatrizb.setText("int[][] matrizB ={{25, -5, 10}, {-10, 21, 54}, {10, -55, -25}};");

        bSumarAyB.setText("Suma Matriz A y Matriz B");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lMensaje2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lMultiplicar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEscalar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bVerResultado))
                    .addComponent(lMatriz)
                    .addComponent(lMensaje1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bSumarAyB)
                        .addComponent(lMatrizb)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lMensaje1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lMatriz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMultiplicar)
                    .addComponent(tfEscalar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bVerResultado))
                .addGap(18, 18, 18)
                .addComponent(lMensaje2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lMatrizb)
                .addGap(18, 18, 18)
                .addComponent(bSumarAyB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arreglo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arreglo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arreglo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arreglo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arreglo2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSumarAyB;
    private javax.swing.JButton bVerResultado;
    private javax.swing.JLabel lMatriz;
    private javax.swing.JLabel lMatrizb;
    private javax.swing.JLabel lMensaje1;
    private javax.swing.JLabel lMensaje2;
    private javax.swing.JLabel lMultiplicar;
    private javax.swing.JTextField tfEscalar;
    // End of variables declaration//GEN-END:variables
}
