/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sentenciascontrol;

import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JRadioButton;
import javax.swing.JCheckBox;

/**
 *
 * @author Armando J. López L.
 */
public class IfElse extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfElse
     */
    public IfElse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgEjer1 = new javax.swing.ButtonGroup();
        lEjer1 = new javax.swing.JLabel();
        pLugaresVisitados = new javax.swing.JPanel();
        chbOmetepe = new javax.swing.JCheckBox();
        chbLaguna = new javax.swing.JCheckBox();
        chbIsland = new javax.swing.JCheckBox();
        chbSanJuan = new javax.swing.JCheckBox();
        bMostrar2 = new javax.swing.JButton();
        lEjer2 = new javax.swing.JLabel();
        pEstadoCivil = new javax.swing.JPanel();
        rbSoltero = new javax.swing.JRadioButton();
        rbCasado = new javax.swing.JRadioButton();
        rbOtro = new javax.swing.JRadioButton();
        bMostrar1 = new javax.swing.JButton();
        lEjer3 = new javax.swing.JLabel();
        tbOpcion = new javax.swing.JToggleButton();
        lEjer4 = new javax.swing.JLabel();
        tfNum1 = new javax.swing.JTextField();
        bValidar4 = new javax.swing.JButton();
        lEjer5 = new javax.swing.JLabel();
        tfNum2 = new javax.swing.JTextField();
        bValidar5 = new javax.swing.JButton();
        bMostrar3 = new javax.swing.JButton();
        lEjer6 = new javax.swing.JLabel();
        tfNum3 = new javax.swing.JTextField();
        bValidar6 = new javax.swing.JButton();
        lEjer7 = new javax.swing.JLabel();
        tfNum4 = new javax.swing.JTextField();
        bValidar7 = new javax.swing.JButton();
        lEjer8 = new javax.swing.JLabel();
        tfNum5 = new javax.swing.JTextField();
        bCalcular8 = new javax.swing.JButton();
        tfNum6 = new javax.swing.JTextField();
        tfNum7 = new javax.swing.JTextField();
        tfNum8 = new javax.swing.JTextField();
        lEjer9 = new javax.swing.JLabel();
        tfNum9 = new javax.swing.JTextField();
        bCalcular9 = new javax.swing.JButton();
        lEjer10 = new javax.swing.JLabel();
        tfNum10 = new javax.swing.JTextField();
        bMostrar10 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Sentencia de Bifurcación if...else de Java");

        lEjer1.setText("1. Muestre un mensaje con la selección realizada");

        pLugaresVisitados.setBorder(javax.swing.BorderFactory.createTitledBorder("Lugares Visitados"));

        chbOmetepe.setText("Ometepe");

        chbLaguna.setText("Laguna de Apoyo");

        chbIsland.setText("Corn Island");

        chbSanJuan.setText("San Juan del Sur");

        bMostrar2.setText("Mostrar");
        bMostrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMostrar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pLugaresVisitadosLayout = new javax.swing.GroupLayout(pLugaresVisitados);
        pLugaresVisitados.setLayout(pLugaresVisitadosLayout);
        pLugaresVisitadosLayout.setHorizontalGroup(
            pLugaresVisitadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLugaresVisitadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pLugaresVisitadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pLugaresVisitadosLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(bMostrar2))
                    .addComponent(chbOmetepe)
                    .addComponent(chbLaguna)
                    .addComponent(chbIsland)
                    .addComponent(chbSanJuan))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        pLugaresVisitadosLayout.setVerticalGroup(
            pLugaresVisitadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLugaresVisitadosLayout.createSequentialGroup()
                .addComponent(chbOmetepe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbLaguna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbIsland)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbSanJuan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bMostrar2))
        );

        lEjer2.setText("2. Muestre un mensaje con las selecciones realizadas");

        pEstadoCivil.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado Civil"));

        bgEjer1.add(rbSoltero);
        rbSoltero.setText("Soltero(a)");

        bgEjer1.add(rbCasado);
        rbCasado.setText("Casado(a)");

        bgEjer1.add(rbOtro);
        rbOtro.setText("Otro");

        bMostrar1.setText("Mostrar");
        bMostrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMostrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pEstadoCivilLayout = new javax.swing.GroupLayout(pEstadoCivil);
        pEstadoCivil.setLayout(pEstadoCivilLayout);
        pEstadoCivilLayout.setHorizontalGroup(
            pEstadoCivilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEstadoCivilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEstadoCivilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbCasado)
                    .addComponent(rbOtro)
                    .addComponent(rbSoltero))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEstadoCivilLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(bMostrar1)
                .addContainerGap())
        );
        pEstadoCivilLayout.setVerticalGroup(
            pEstadoCivilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEstadoCivilLayout.createSequentialGroup()
                .addComponent(rbSoltero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbCasado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbOtro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bMostrar1))
        );

        lEjer3.setText("3. Muestre un mensaje con el estado del botón");

        tbOpcion.setText("Opción A");
        tbOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbOpcionActionPerformed(evt);
            }
        });

        lEjer4.setText("4. Valide la mayoría de edad (>=21 años)");

        bValidar4.setText("Validar");
        bValidar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bValidar4ActionPerformed(evt);
            }
        });

        lEjer5.setText("5. Valide si el número es una calificación válida (0 - 100)");

        bValidar5.setText("Validar");
        bValidar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bValidar5ActionPerformed(evt);
            }
        });

        bMostrar3.setText("Mostrar");
        bMostrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMostrar3ActionPerformed(evt);
            }
        });

        lEjer6.setText("6. Valide si la calificación es aprobada o reprobada");

        bValidar6.setText("Validar");
        bValidar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bValidar6ActionPerformed(evt);
            }
        });

        lEjer7.setText("7. Valide si el año es bisiesto");

        bValidar7.setText("Validar");
        bValidar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bValidar7ActionPerformed(evt);
            }
        });

        lEjer8.setText("8. Calcule el mayor de los números");

        bCalcular8.setText("Calcular");
        bCalcular8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCalcular8ActionPerformed(evt);
            }
        });

        lEjer9.setText("9. Calcule la cantidad de días del mes");

        bCalcular9.setText("Calcular");
        bCalcular9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCalcular9ActionPerformed(evt);
            }
        });

        lEjer10.setText("10. Muestre el reconocimiento según la calificación (E, MB, B, D)");

        bMostrar10.setText("Mostrar");
        bMostrar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMostrar10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lEjer1)
                    .addComponent(lEjer2)
                    .addComponent(pLugaresVisitados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lEjer3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tbOpcion)
                                .addGap(18, 18, 18)
                                .addComponent(bMostrar3)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lEjer8)
                                .addGap(33, 33, 33))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCalcular8))
                    .addComponent(lEjer4)
                    .addComponent(lEjer5)
                    .addComponent(lEjer6)
                    .addComponent(lEjer7)
                    .addComponent(lEjer9)
                    .addComponent(lEjer10)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfNum10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bMostrar10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bValidar7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bValidar6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bValidar5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bValidar4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bCalcular9)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEjer1)
                    .addComponent(lEjer4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bValidar4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lEjer5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bValidar5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lEjer6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bValidar6)))
                    .addComponent(pEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lEjer7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bValidar7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lEjer8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNum5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bCalcular8)
                            .addComponent(tfNum6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNum7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNum8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lEjer9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNum9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bCalcular9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lEjer10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNum10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bMostrar10))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lEjer2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pLugaresVisitados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lEjer3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbOpcion)
                            .addComponent(bMostrar3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bMostrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMostrar1ActionPerformed
        // TODO add your handling code here:
        int option = getPosition();

        if (option == 0) {
            JOptionPane.showMessageDialog(null, "Soltero/a");
        } else if (option == 1) {
            JOptionPane.showMessageDialog(null, "Casado/a");
        } else if (option == 2) {
            JOptionPane.showMessageDialog(null, "Otro/a");
        } else {
            JOptionPane.showMessageDialog(null, "Que");

        }
    }//GEN-LAST:event_bMostrar1ActionPerformed

    private void bMostrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMostrar2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, getVisitedPlaces());

    }//GEN-LAST:event_bMostrar2ActionPerformed

    private void tbOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbOpcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbOpcionActionPerformed

    private void bMostrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMostrar3ActionPerformed
        if (tbOpcion.isSelected()) {
            JOptionPane.showMessageDialog(null, "Presionado");
        } else {
            JOptionPane.showMessageDialog(null, "No presionado");

        }
    }//GEN-LAST:event_bMostrar3ActionPerformed

    private void bValidar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bValidar4ActionPerformed
        int num = Integer.parseInt(tfNum1.getText());
        if (num >= 21) {
            JOptionPane.showMessageDialog(null, "Mayor de edad");
        } else if (num <= 0) {
            JOptionPane.showMessageDialog(null, "Que");
        } else {
            JOptionPane.showMessageDialog(null, "Menor de edad");
        }
    }//GEN-LAST:event_bValidar4ActionPerformed

    private void bValidar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bValidar5ActionPerformed
        // TODO add your handling code here:
        int num = Integer.parseInt(tfNum2.getText());
        if (num >= 0 & num <= 100) {
            JOptionPane.showMessageDialog(null, "Valido");
        } else {
            JOptionPane.showMessageDialog(null, "Que");
        }
    }//GEN-LAST:event_bValidar5ActionPerformed

    private void bValidar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bValidar6ActionPerformed
        // TODO add your handling code here:
        int num = Integer.parseInt(tfNum3.getText());
        if (num < 0 || num <= 60) {
            JOptionPane.showMessageDialog(null, "Reprobado");
        } else {
            JOptionPane.showMessageDialog(null, "Aprobado");
        }
    }//GEN-LAST:event_bValidar6ActionPerformed

    private void bValidar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bValidar7ActionPerformed
        // TODO add your handling code here:
        int num = Integer.parseInt(tfNum3.getText());
        if ((num % 4 == 0) && (num % 100 != 0) || (num % 400 == 0)) {
            JOptionPane.showMessageDialog(null, "Bisiesto");
        } else {
            JOptionPane.showMessageDialog(null, "No bisiesto");
        }
    }//GEN-LAST:event_bValidar7ActionPerformed

    private void bCalcular8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCalcular8ActionPerformed
        // TODO add your handling code here:
        try {
            int num1 = Integer.parseInt(tfNum5.getText());
            int num2 = Integer.parseInt(tfNum6.getText());
            int num3 = Integer.parseInt(tfNum7.getText());
            int num4 = Integer.parseInt(tfNum8.getText());

            List<Integer> numList = new ArrayList<>();
            numList.add(num1);
            numList.add(num2);
            numList.add(num3);
            numList.add(num4);

            int num;
            int mayor = 0;
            for (int i = 0; i < numList.size(); i++) {
                num = numList.get(i);

                if (i == 0) {
                    mayor = num;
                }

                if (num > mayor) {
                    mayor = num;
                }
            }
            JOptionPane.showMessageDialog(null, "El mayor es: " + mayor);
        } catch (Exception ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Que");
        }
    }//GEN-LAST:event_bCalcular8ActionPerformed

    private void bCalcular9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCalcular9ActionPerformed
        // TODO add your handling code here:
        int mes = Integer.parseInt(tfNum9.getText());
        String r = "El mes tiene: ";
        if (mes == 2) {
            r = r + "28 dias";
            JOptionPane.showMessageDialog(null, r);
        } else if (checkIfHas31Days(mes)) {
            r = r + "31 dias";
            JOptionPane.showMessageDialog(null, r);
        } else {
            r = r + "30 dias";
            JOptionPane.showMessageDialog(null, r);
        }
    }//GEN-LAST:event_bCalcular9ActionPerformed

    private void bMostrar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMostrar10ActionPerformed
        // TODO add your handling code here:
        int score = Integer.parseInt(tfNum10.getText());
        String r = "";
        try {
            if (score >= 90) {
                r = "E";
                JOptionPane.showMessageDialog(null, r);
            } else if (score < 90 && score >= 85) {
                r = "MB";
                JOptionPane.showMessageDialog(null, r);
            } else if (score < 85 && score >= 75) {
                r = "B";
                JOptionPane.showMessageDialog(null, r);
            } else if (score < 75) {
                r = "D";
                JOptionPane.showMessageDialog(null, r);
            }
        } catch (Exception ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Que");
        }
    }//GEN-LAST:event_bMostrar10ActionPerformed

    private boolean checkIfHas31Days(int monthToCheck) {
        boolean r = false;
        List<Integer> month = new ArrayList<>();
        month.add(1);
        month.add(3);
        month.add(5);
        month.add(7);
        month.add(8);
        month.add(10);
        month.add(12);

        for (int i = 0; i < month.size(); i++) {
            if (month.get(i) == monthToCheck) {
                r = true;
            }
        }
        return r;
    }

    private int getPosition() {
        int option = 0;
        List<JRadioButton> options = new ArrayList<>();
        options.add(rbSoltero);
        options.add(rbCasado);
        options.add(rbOtro);

        for (int i = 0; i < options.size(); i++) {
            if (options.get(i).isSelected()) {
                option = options.indexOf(options.get(i));
            }
        }

        return option;
    }

    private String getVisitedPlaces() {
        String option = "He visitado: ";
        List<JCheckBox> options = new ArrayList<>();
        int counter = 0;
        options.add(chbIsland);
        options.add(chbLaguna);
        options.add(chbOmetepe);
        options.add(chbSanJuan);

        for (int i = 0;
                i < options.size(); i++) {
            if (options.get(i).isSelected()) {
                option = option + options.get(i).getText() + " ";
                counter++;
            }
        }

        if (counter == 0) {
            option = option + "ningun lado xd";
        }
        return option;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCalcular8;
    private javax.swing.JButton bCalcular9;
    private javax.swing.JButton bMostrar1;
    private javax.swing.JButton bMostrar10;
    private javax.swing.JButton bMostrar2;
    private javax.swing.JButton bMostrar3;
    private javax.swing.JButton bValidar4;
    private javax.swing.JButton bValidar5;
    private javax.swing.JButton bValidar6;
    private javax.swing.JButton bValidar7;
    private javax.swing.ButtonGroup bgEjer1;
    private javax.swing.JCheckBox chbIsland;
    private javax.swing.JCheckBox chbLaguna;
    private javax.swing.JCheckBox chbOmetepe;
    private javax.swing.JCheckBox chbSanJuan;
    private javax.swing.JLabel lEjer1;
    private javax.swing.JLabel lEjer10;
    private javax.swing.JLabel lEjer2;
    private javax.swing.JLabel lEjer3;
    private javax.swing.JLabel lEjer4;
    private javax.swing.JLabel lEjer5;
    private javax.swing.JLabel lEjer6;
    private javax.swing.JLabel lEjer7;
    private javax.swing.JLabel lEjer8;
    private javax.swing.JLabel lEjer9;
    private javax.swing.JPanel pEstadoCivil;
    private javax.swing.JPanel pLugaresVisitados;
    private javax.swing.JRadioButton rbCasado;
    private javax.swing.JRadioButton rbOtro;
    private javax.swing.JRadioButton rbSoltero;
    private javax.swing.JToggleButton tbOpcion;
    private javax.swing.JTextField tfNum1;
    private javax.swing.JTextField tfNum10;
    private javax.swing.JTextField tfNum2;
    private javax.swing.JTextField tfNum3;
    private javax.swing.JTextField tfNum4;
    private javax.swing.JTextField tfNum5;
    private javax.swing.JTextField tfNum6;
    private javax.swing.JTextField tfNum7;
    private javax.swing.JTextField tfNum8;
    private javax.swing.JTextField tfNum9;
    // End of variables declaration//GEN-END:variables
}
