/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sentenciascontrol;

import javax.swing.JDesktopPane;

/**
 *
 * @author Armando J. López L.
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Logicos ifLogicos = new Logicos();
    Aritmeticos ifAritmeticos = new Aritmeticos();
    IfElse ifIfElse = new IfElse();
    Switch ifSwitch = new Switch();
    For ifFor = new For();
    ForEach ifForEach = new ForEach();
    Do ifDo = new Do();
    While ifWhile = new While();
    Arreglo1 ifArreglo1 = new Arreglo1();
    Arreglo2 ifArreglo2 = new Arreglo2();
    Consola ifConsola = new Consola();
    Cadenas ifCadenas = new Cadenas();
    
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpEscritorio = new javax.swing.JDesktopPane();
        mbPrincipal = new javax.swing.JMenuBar();
        mOperadoresExpresiones = new javax.swing.JMenu();
        miLogicos = new javax.swing.JMenuItem();
        miAritmeticos = new javax.swing.JMenuItem();
        miConsola = new javax.swing.JMenuItem();
        mBifurcacion = new javax.swing.JMenu();
        miIfElse = new javax.swing.JMenuItem();
        miSwitch = new javax.swing.JMenuItem();
        mRepeticion = new javax.swing.JMenu();
        miFor = new javax.swing.JMenuItem();
        miForEach = new javax.swing.JMenuItem();
        miDo = new javax.swing.JMenuItem();
        miWhile = new javax.swing.JMenuItem();
        mArreglos = new javax.swing.JMenu();
        miAgregar = new javax.swing.JMenuItem();
        miArreglo2 = new javax.swing.JMenuItem();
        miCadenas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sentencias de Java");
        setExtendedState(MAXIMIZED_BOTH);

        javax.swing.GroupLayout dpEscritorioLayout = new javax.swing.GroupLayout(dpEscritorio);
        dpEscritorio.setLayout(dpEscritorioLayout);
        dpEscritorioLayout.setHorizontalGroup(
            dpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        dpEscritorioLayout.setVerticalGroup(
            dpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );

        mOperadoresExpresiones.setText("Operadores y Expresiones");

        miLogicos.setText("Lógicos");
        miLogicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogicosActionPerformed(evt);
            }
        });
        mOperadoresExpresiones.add(miLogicos);

        miAritmeticos.setText("Aritméticos");
        miAritmeticos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAritmeticosActionPerformed(evt);
            }
        });
        mOperadoresExpresiones.add(miAritmeticos);

        miConsola.setText("Consola");
        miConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsolaActionPerformed(evt);
            }
        });
        mOperadoresExpresiones.add(miConsola);

        mbPrincipal.add(mOperadoresExpresiones);

        mBifurcacion.setText("Bifurcación");

        miIfElse.setText("if...else");
        miIfElse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miIfElseActionPerformed(evt);
            }
        });
        mBifurcacion.add(miIfElse);

        miSwitch.setText("switch");
        miSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSwitchActionPerformed(evt);
            }
        });
        mBifurcacion.add(miSwitch);

        mbPrincipal.add(mBifurcacion);

        mRepeticion.setText("Repetición");

        miFor.setText("for");
        miFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miForActionPerformed(evt);
            }
        });
        mRepeticion.add(miFor);

        miForEach.setText("for each");
        miForEach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miForEachActionPerformed(evt);
            }
        });
        mRepeticion.add(miForEach);

        miDo.setText("do");
        miDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDoActionPerformed(evt);
            }
        });
        mRepeticion.add(miDo);

        miWhile.setText("while");
        miWhile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miWhileActionPerformed(evt);
            }
        });
        mRepeticion.add(miWhile);

        mbPrincipal.add(mRepeticion);

        mArreglos.setText("Arreglos");

        miAgregar.setText("Arreglos Unidimensionales");
        miAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAgregarActionPerformed(evt);
            }
        });
        mArreglos.add(miAgregar);

        miArreglo2.setText("Arreglos Bidimensionales");
        miArreglo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miArreglo2ActionPerformed(evt);
            }
        });
        mArreglos.add(miArreglo2);

        miCadenas.setText("Cadenas de caracteres");
        miCadenas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadenasActionPerformed(evt);
            }
        });
        mArreglos.add(miCadenas);

        mbPrincipal.add(mArreglos);

        setJMenuBar(mbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miLogicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogicosActionPerformed
        this.dpEscritorio.add(this.ifLogicos);
        this.ifLogicos.setVisible(true);
    }//GEN-LAST:event_miLogicosActionPerformed

    private void miAritmeticosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAritmeticosActionPerformed
            this.dpEscritorio.add(this.ifAritmeticos);
            this.ifAritmeticos.setVisible(true);
            
    }//GEN-LAST:event_miAritmeticosActionPerformed

    private void miIfElseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miIfElseActionPerformed
        this.dpEscritorio.add(this.ifIfElse);
        this.ifIfElse.setVisible(true);
    }//GEN-LAST:event_miIfElseActionPerformed

    private void miSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSwitchActionPerformed
        this.dpEscritorio.add(this.ifSwitch);
        this.ifSwitch.setVisible(true);
    }//GEN-LAST:event_miSwitchActionPerformed

    private void miForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miForActionPerformed
        this.dpEscritorio.add(this.ifFor);
        this.ifFor.setVisible(true);
    }//GEN-LAST:event_miForActionPerformed

    private void miForEachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miForEachActionPerformed
        this.dpEscritorio.add(this.ifForEach);
        this.ifForEach.setVisible(true);
    }//GEN-LAST:event_miForEachActionPerformed

    private void miDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDoActionPerformed
        this.dpEscritorio.add(this.ifDo);
        this.ifDo.setVisible(true);
    }//GEN-LAST:event_miDoActionPerformed

    private void miWhileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miWhileActionPerformed
        this.dpEscritorio.add(this.ifWhile);
        this.ifWhile.setVisible(true);
    }//GEN-LAST:event_miWhileActionPerformed

    private void miAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAgregarActionPerformed
        // TODO add your handling code here:
        this.dpEscritorio.add(this.ifArreglo1);
        this.ifArreglo1.setVisible(true);
    }//GEN-LAST:event_miAgregarActionPerformed

    private void miArreglo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miArreglo2ActionPerformed
        // TODO add your handling code here:
        this.dpEscritorio.add(this.ifArreglo2);
        this.ifArreglo2.setVisible(true);
                
    }//GEN-LAST:event_miArreglo2ActionPerformed

    private void miConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsolaActionPerformed
        this.dpEscritorio.add(this.ifConsola);
        this.ifConsola.setVisible(true);
    }//GEN-LAST:event_miConsolaActionPerformed

    private void miCadenasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadenasActionPerformed
        this.dpEscritorio.add(this.ifCadenas);
        this.ifCadenas.setVisible(true);
    }//GEN-LAST:event_miCadenasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpEscritorio;
    private javax.swing.JMenu mArreglos;
    private javax.swing.JMenu mBifurcacion;
    private javax.swing.JMenu mOperadoresExpresiones;
    private javax.swing.JMenu mRepeticion;
    private javax.swing.JMenuBar mbPrincipal;
    private javax.swing.JMenuItem miAgregar;
    private javax.swing.JMenuItem miAritmeticos;
    private javax.swing.JMenuItem miArreglo2;
    private javax.swing.JMenuItem miCadenas;
    private javax.swing.JMenuItem miConsola;
    private javax.swing.JMenuItem miDo;
    private javax.swing.JMenuItem miFor;
    private javax.swing.JMenuItem miForEach;
    private javax.swing.JMenuItem miIfElse;
    private javax.swing.JMenuItem miLogicos;
    private javax.swing.JMenuItem miSwitch;
    private javax.swing.JMenuItem miWhile;
    // End of variables declaration//GEN-END:variables
}
